### ISSUE TITLE
Any protocol documentations available?

### ISSUE THREAD

**Issue by therealjg** [RFStorm/mousejack#7]
Hi,

is there any documentation about the underlying protocols of the affected devices? 

Sniffing and simply replaying the payloads is possible, but interpreting is not. When sniffing a Logitech connection, the payloads differs completely from the Logitech specifications of the HID++ protocol.

**Comment by marcnewlin** [comment]
Peter Wu has some Logitech HID++ and related documentation hosted on his website. It sounds like you are already aware of this, but I am mentioning it so that others can find it as well. 

https://lekensteyn.nl/files/logitech/

The slides from my ToorCon talk include some RF protocol information regarding Logitech wireless mice. 

https://drive.google.com/file/d/0B4Pb6jGAmjoKQ3hlZDFxUHVqRkU/view

The KeyKeriki project and subsequent work by Travis Goodspeed and Samy Kamkar documents the packet format used by the previous generation of XOR-encrypted Microsoft wireless keyboards. 

http://www.remote-exploit.org/articles/keykeriki_v2_0__8211_2_4ghz/
http://travisgoodspeed.blogspot.com/2011/02/promiscuity-is-nrf24l01s-duty.html
http://samy.pl/keysweeper/

**Comment by therealjg** [comment]
Hey,

thanks for the documents. The slides of the ToorCon talk helped me out. Now, I understand the protocol of the wireless mice. 

Thanks a lot!
