### ISSUE TITLE
HackRF

### ISSUE THREAD

**Issue by lineasmagicas** [RFStorm/mousejack#8]
Hi! Its Works with HackRF? 

Thanks

**Comment by marcnewlin** [comment]
It is difficult to implement two way communication between a software defined radio and wireless mouse USB dongle due to timing constraints. There are two things to consider.

### ACK Timeouts

The HackRF us a half-duplex SDR, meaning that it cannot transmit and receive at the same time. In order to effectively communicate with a wireless mouse USB dongle, it is necessary to be able to receive ACK packets. 

The nRF24L series of transceivers has ACK timeouts as low as 250 microseconds. To decode ACKs in this window, a SDR would need to switch from transmit to receive in well under 250 microseconds. USB latency alone makes this impossible to do from the host computer, so an implementation would need to be done in FPGA.

### Retune Time

This is not a hard constraint, but adds complexity to the research process. The nRF24L Enhanced Shockburst protocol is not inherently a frequency hopping protocol, but the transceivers are capable of fast retuning, and most vendors use a "frequency agility" mechanism to change channels to avoid interference. 

The retune time on the nRF24L chips is very low compared to the HackRF, making it difficult to sniff 100% of the packets without dedicated hardware.

**Comment by lineasmagicas** [comment]
Thanks Marc.
